### ISSUE TITLE
Where can I get ConceptNet.json

### ISSUE THREAD

**Issue by LZY-the-boys** [LiqiangJing/TEAM#1]
Hello , thanks for your great work, I am wondering that how to get the ConceptNet.json in your code:
```
concept_dict = json.load(open("ConceptNet.json", "r", encoding="utf-8"))
FileNotFoundError: [Errno 2] No such file or directory: 'ConceptNet.json'
```

**Comment by LiqiangJing** [comment]
Well, I will later upload this file to the cloud disk link in the Related Data section.

**Comment by LiqiangJing** [comment]
> Hello , thanks for your great work, I am wondering that how to get the ConceptNet.json in your code:
> 
> ```
> concept_dict = json.load(open("ConceptNet.json", "r", encoding="utf-8"))
> FileNotFoundError: [Errno 2] No such file or directory: 'ConceptNet.json'
> ```

We have uploaded all these knowledge-related files vai this link https://drive.google.com/drive/folders/13vuYwJzGEnvV3r-gJxihVNjvIiuGrO6q?usp=share_link

**Comment by LZY-the-boys** [comment]
Thanks for the response ! Now I can load concept files, however, I run into another problem: I cannot read `train_adj.pkl`
```
<class '_pickle.UnpicklingError'> pickle data was truncated
> /home/TEAM/dataset.py(36)__init__()
-> self.adj = pickle.load(adj)
```
I download it from google drive again and still encounter such error. So would you please to re upload it ? many thanks!

**Comment by LiqiangJing** [comment]
> 

OK. I will check the file and upload it.

**Comment by LiqiangJing** [comment]
> Thanks for the response ! Now I can load concept files, however, I run into another problem: I cannot read `train_adj.pkl`
> 
> ```
> <class '_pickle.UnpicklingError'> pickle data was truncated
> > /home/TEAM/dataset.py(36)__init__()
> -> self.adj = pickle.load(adj)
> ```
> 
> I download it from google drive again and still encounter such error. So would you please to re upload it ? many thanks!

We have uploaded adj.zip to update this file.

**Comment by Voolion** [comment]
thanks for you work, i am wondering where i can get you images datasets

**Comment by LiqiangJing** [comment]
> thanks for you work, i am wondering where i can get you images datasets

For the original image dataset, you can refer to this link https://github.com/LCS2-IIITD/Multimodal-Sarcasm-Explanation-MuSE/tree/main.
