### ISSUE TITLE
Regarding the Faster-RCNN implementation proposed in the research paper

### ISSUE THREAD

**Issue by bl0nder** [LiqiangJing/TEAM#3]
I am an undergraduate student and am trying to implement your paper as a part of my research. Your paper states that your model utilises a Faster-RCNN for best performance. However, the code given by you makes use of a vision transformer (from the ablation study is my guess). Could you kindly provide the code for the model using the Faster-RCNN?
Thank you.

**Comment by LiqiangJing** [comment]
If you read the code carefully, you will find the vit-related codes aren't utilized. The Faster RCNN is run offline.

**Comment by bl0nder** [comment]
Just to clarify, does that mean that running `bsl_train.py` trains the model with the best reported performance? If not, could you kindly point to which variant of the model from the ablation study it corresponds to? I am asking this since up till now, I was under the impression that running `bsl_train.py` would train the **TEAM w/-Visual** variant of the model.
Thank you for your help.

**Comment by LiqiangJing** [comment]
Yeah, running bsl_train.py trains the model with the best reported performance

**Comment by bl0nder** [comment]
Thank you
