### ISSUE TITLE
img file

### ISSUE THREAD

**Issue by Lieberk** [LiqiangJing/TEAM#5]
Thanks for your code sharing. I want to run the code project, but I can't find the data set of the picture. Is it missing from the upload, or I can't find it here.

**Comment by LiqiangJing** [comment]
For all images, you can find them in the original dataset repo. 在 2023年11月15日，下午9:51，Lizhi Chen ***@***.***> 写道：﻿
Thanks for your code sharing. I want to run the code project, but I can't find the data set of the picture. Is it missing from the upload, or I can't find it here.
