### ISSUE TITLE
Faster RCNN

### ISSUE THREAD

**Issue by bl0nder** [LiqiangJing/TEAM#6]
Hello
Could you provide an inference-ready implementation of the Faster-RCNN you used? I want to run some experiments and would be quite grateful if you could provide the same since you have already used the same for your paper.
Thank you

**Comment by LiqiangJing** [comment]
We have released the inference data

**Comment by bl0nder** [comment]
Hi, I should have mentioned, I need to run these experiments on some other data and not the inference one. In other words, I am using data that is not a part of the MORE dataset that you used. Hence, I need to extract the object-attribute pairs for the images in my data and am requesting your help here.

**Comment by LiqiangJing** [comment]
We run Faster RCNN for inference, you can refer to the official repo
